server:
  port: ${APP_PORT:8080}

spring:
  profiles: 
    active: default

logging:
  level:
    root: ${ROOT_LEVEL:info}
    com:
      smartkuk: ${APP_LEVEL:debug}

app:
  name: ${APP_NAME:spring-boot-rest}

---

spring:
  profiles: dev
