server:
  port: ${APP_PORT:8080}

spring:
  application:    name: ${APP_NAME:latest}
  profiles:
    active: default

logging:
  level:
    root: ${ROOT_LEVEL:info}
    com:
      smartkuk: ${APP_LEVEL:debug}

app:
  name: ${APP_NAME:latest}

---

spring:
  profiles: dev
